### ISSUE TITLE
Beenden mit Ctrl-C gibt Shared Memory nicht mehr frei

### ISSUE THREAD

**Issue by amp-man** [amp-man/reversi#19]
Hey, wenn man den sysprak-client mit ctrl-c beendet wird das Shared Memory nicht mehr freigegeben.

Es wäre gut wenn wir das irgendwie lösen könnten, da ansonsten nach einigen Aufrufen kein Speicher mehr verfügbar ist.

Im Moment kann man sich das shm mit dem Terminal Befehl `ipcs` anzeigen lassen und dann mit z.B. `ipcrm -m 65537` wieder löschen.

**Comment by amp-man** [comment]
Zitat aus Aufgabenblatt 2:

> • Es ist darauf zu achten, dass die SHM-Segmente bei Prozessende wieder explizit entfernt werden (Hinweis: shmctl(), IPC_RMID). Sie können über die Kommandozeile mittels ipcs die reservierten SHM-Bereiche einsehen und mittels ipcrm Speicherbereiche, die durch fehlerhafte Testversionen des Clients nicht entfernt wurden, manuell entfernen.

**Comment by amp-man** [comment]
@PWehr599 @mariuskiefer

**Comment by PWehr599** [comment]
In fork wird readcommandfromserver aufgerufen. Solange dieses Programm nicht beendet wird das deleteSHM() am ende des Programms nicht ausgeführt und die Segmente bleiben erhalten. Aus welchem Grund beendet readcommandfromserver nicht und bleibt in endlosaufruf. Wenn diese auskommentiert ist werden die sharedMemory Segmente auch wieder entfernt . Ich kenn mit der Connector Methode jetzt nicht so gut aus da kenn ich das Problem nicht.

**Comment by amp-man** [comment]
Ich __glaube__ ich hab das Memory Leak repariert, siehe hier:
c374784adc52e94a3fc65f663e004357cbb93800

**Comment by PWehr599** [comment]
mit deattach löscht du einfach das SHM-Segment(shmctl)
für deattachen brauchst du shmdt:
void deattachSHM(void *shm)
{
    if (shmdt(shm) == -1){
        perror ("ERROR: didn't deattach");
    }
}
Warum muss das Segment deattached werden?
die prozesse können ja dann nicht mehr drauf zugreifen

**Comment by amp-man** [comment]
Ok, kannst du das dann implementieren? Bin gespannt ob es mit deiner Methode funktioniert.

> Warum muss das Segment deattached werden?
> die prozesse können ja dann nicht mehr drauf zugreifen

Doch, können sie schon so weit ich weiß. Siehe meinen Kommentar oberhalb des 
deattachSHM() Methodenaufrufs:

`
Hier wird das Shared Memory unlinked. Beide Prozesse haben immer noch darauf Zugriff.
 Dies ist eine Vorbereitung für einen Programmabbruch, bei dem das Programm nicht normal terminieren kann.
Das SHM bleibt trotzdem bestehen und kann von bereits attached Prozessen genutzt werden.
 Das Betriebssystem löscht das SHM dann automatisch wenn kein Prozess mehr darauf zugreift.
`

**Comment by amp-man** [comment]
Vielleicht hätte ich die Methode „unlinkSHM()“ nennen sollen um Missverständnissen vorzubeugen :)

**Comment by amp-man** [comment]
@PWehr599 Ich hab es jetzt mal auf einem neuen Branch so implementiert wie du vorgeschlagen hast, aber leider bleibt jetzt das SHM Segment bestehen nach Programmabbruch:
Siehe hier: bfdbd47616493282bbc898bb5815b80dafea561a

**Comment by amp-man** [comment]
Btw: In dem Kommentar auf SO hab ich den Lösungsansatz gefunden mit dem unlinken des SHM:
[Remove posix shared memory when not in use?](https://stackoverflow.com/a/13445202)

**Comment by PWehr599** [comment]
Ich wusste nicht genau wie das mit dem Unlinken gemeint war. Wusste ehrlichgesagt  gar nicht das man noch drauf zugreifen kann wenn es unlinked wurde.Das stimmt, bis jetzt wird zwar das SHM unlinked aber nicht gelöscht . Ich probier das mal nach dem StackOverflow artikel zu implementieren. Vielleicht können wir es auch auf Zeit setzen, wenn kein Prozess in 15 Sekunden drauf zugreift wird es automatisch gelöscht zB

**Comment by PWehr599** [comment]
[http://www.dps.uibk.ac.at/~tf/lehre/ss04old/bs/tutorials/sharedmemory/15.htm]
 ZB hier , dachte das wär nicht möglich , aber bin gespannt ob es funktioniert

**Comment by PWehr599** [comment]
[http://www.dps.uibk.ac.at/~tf/lehre/ss04old/bs/tutorials/sharedmemory/15.htm](url)

**Comment by PWehr599** [comment]
Kurze Sache mit shmctl wird das SHM gelöscht. mit unlink SHM wird das gleiche wie bei delete SHM gemacht
