### ISSUE TITLE
SHM gamefield in thinker auslesen

### ISSUE THREAD

**Issue by PWehr599** [amp-man/reversi#21]
Weiss jemand wie ich das SHM gamefield im Thinker aufrufen kann ? ich bräuchte es um es in ein array zu lesen.

**Comment by amp-man** [comment]
Hey, ich hatte dir da was falsches erzählt in der Uni, wir hatten im thinker Prozess bis jetzt noch nicht auf das GameField SHM zugreifen können, da ist noch irgend ein kleiner Bug drin (kann sein dass Basti das schon gelöst hat)

**Comment by XPloadED** [comment]
Ich mein shared memory war ja auch ursprünglich eigentlich euer ding. Ich habs jetzt schon mehrfach probiert aber hat am ende trotzdem nie funktioniert(weiß auch nicht so ganz was das Problem ist ... sobald wir die dimensionen in startgameplay bekommen erzeugen wir das shmgamefield und legen die id im entries strucht ab. ...passt das shm selbst nicht?, wird das geparste gamefield nicht richtig im shm abgelegt?... konnte gameFieldToString() bei meinen Versuchen im thinker zwar ausführen, das Spielfeld selbst wurde aber nicht ausgegeben, der Ramen, also ABCD und die nummern aber schon, also ka wo das problem liegt). Kann auch sein dass das shmgamefield segment selber eigentlich passt aber das ablegen des gamefields darin nicht stimmt() ... setzen wir nicht eigentlich nach den attach befehlen den pointer vom shm zurück auf das local struct das wir eigentlich da reinpacken wollten?.
 setSHM() (thinker.c) funktioniert denk ich auch nicht so wie angedacht weils ja nichts an den thinker process übergibt sondern einfach die thinker.c methode setSHM aus dem connector prozess aufruft, was ja nicht das ziel ist(?). Der bessere Ansatz ist denk ich im signalhandler in thinker.c aus dem schon existierenden entries struct die gamefield_id zu attachen(wenn das sig geschickt wurde muss die gamefield_id auch von der abfolge her im entries struct liegen). Hatte in meinen versuchen eine globale variable in thinker.c auf 0 gesetzt und die im signalhandler dann geprüft ob sie 0 ist, dann das gameField attachen und die variable auf 1 setzen (damits eben nur einmal attached wird, keine Ahnung obs da ne bessere lösung für gibt). Select() ist da auch nicht optimal ... stimmt was mim auslesen aus dem shm nicht dann rattert die pipe mit 0 byte gelesen durch bis ein timeout string vom server kommt. Vlt versteht ihr das besser, schauts euch mal an.


Der aktuellste Stand ist ja in feature_connector. Hab da select() noch hinzugefügt @mariuskiefer , müsstest da vlt  nochmal drüber schauen(dann könnten wirs mal wieder auf master pushen).

Um die think (~such gültigen spielzug) methode zu machen brauchst du auch erstmal nur das strtuct. Implementier die Funktion halt solang das shm nicht funktioniert erstmal im connector wo das struct existiert (und auch richtig ausgegeben wird) ... das können wir ja dann später easy in den thinker switchen(ob das struct im shm liegt oder sonst wo ist vom zugriff später ja dann das selbe ~?).
Ich mein du musst das eh nicht mehr in ein array lesen. Das gamefield lliegt ja schon in der struct unter data und die Dimensionen werden durch cols und rows angegeben. Mit den Werten müsstest du eigentlich nurnoch über die Einträge iterieren und dann bei jedem Feld die Felder daneben (~bis zum rand jeweils) prüfen ob durch setzen des steins ein gültiger spielzug  entstehen würde(dabei ist denk ich auch relevant welcher spieler wir sind, also welche farbe wir sind, je nachdem muss dann auf 1 oder 2 geprüft werden). Wenn ja dann senden wir einfach direkt den erst besten über die pipe an den connector(bräuchten dann halt ne unterfunktion die aus der combination rows und cols den richtigen string erzeugt, vom prinzip ähnlich zu gameFieldABC() aus gamefield.c, falls du den ansatz verfolgen willst).

**Comment by PWehr599** [comment]
Die sharedmem.c war unser Ding das stimmt, wie das allerdings im Connector aufgebaut ist weiß ich nicht ,das war ja euer Ding. Solche Probleme die oben genannt werden mit SHM passieren glaub ich relativ häufig,auch wenn das mein Ding war.  Ich muss es in ein array einlesen, dadurch kann ich sehr viel einfacher mit arbeiten. Das iterieren mit einer Struct ist um einiges nerviger. Das gameFeld mit Rahmen brauch ich für den Thinker  , das ist ja da um das Spielfeld an der Kommandozeile auszugeben und das lese ich dann in ein Array ein ,wie gesagt.   Die SpielfeldKoordinaten die von einem Array zurückgegeben werden sind ja gleich. Die müssen dann halt in E3 zb umgeschrieben werden. Nachdem der Spielzug geschickt wurde wird das Array dann wieder gelöscht Eine funktion zu erstellen die die Struct in ein array schreibt müsste keine arbeit sein. Den Ansatz nur mit der Struct zu arbieten würde ich nur sehr sehr ungern verfolgen.
Zu der Farbe und die Spieler 1 und 2 : Das sollte auch einfach aus dem SHM aufgerufen werden können . Die Farbe hab ich mit defines gemacht da kann man einfach zwischen den Farben ändern (variable die dann zu 1oder 2 geändert werden kann ),die Logik bleibt ja  die Gleiche . Ich muss es nur testen können.
Für das schicken des Spielmoves:
mann kann ja koordinate eins und zwei als zahlen in eine Funktion schicken, wie gesagt müsste das kein problem sein.
Hab auch schon geschaut im feature_connector. Ich wollte nur erst die Regeln seperat zusammenschreiben bevor ich mich an das Projekt im ganzen ranmache.

**Comment by XPloadED** [comment]
Naja wie du meinst. In meinen Augen umfasst halt sharememory  nicht nur die manpage funktionen in wrapper funktionen zu packen sondern auch die eigentliche implementierung in der Abfolge. Schon ok dass das gamefieldshm seperat erst in der Protokoll Aufgabe angelegt werden soll. Dann aber (scheinbar) nicht weiter zu machen weil das noch nicht funktioniert obwohl eure frühere Aufgabe das Thema umfasst hat(und das testen offensichtlich auch ausm connector gehen würde ... dort existiert das gamefield struct +  gameFieldToString ohne weiteres) ist schon etwas komisch. Entweder selber versuchen das mit dem shm hin zu bekommen um dann im thinker implementieren zu können ... oder halt temporär nur mit der struct selbst arbeiten. Aber einfach füße hochlegen find ich mist. Ist ja nicht so als hätten wir an euren commits nicht auch oft genug etwas überarbeitet, da strikt zu sagen ~nicht meine Aufgabe, muss ich nicht wissen~ find ich dann schon etwas schwach ...
Sollte ja klar sein dass jeder verstehen sollte wo was warum passiert, auch wenns nicht direkt im eigenen Aufgabenteil gefragt ist. Gerade wenn der eigene Task davon betroffen ist.


Ist halt etwas mekwürdig unsere eigene Ausgabe die wir aus dem gamefield struct erstellen, welche wir aus der servernachricht geparst haben  dann nooochmal zu parsen. Aber mach wie du meinst solange es funktioniert ist mir das ehrlich gesagt gleich. War alles nur als tip gedach so wie ich halt rangegangen wäre, aber wenn du schon weist wie dus machen willst umso besser.

**Comment by PWehr599** [comment]
Da reden wir am Montag drüber. Ich will mein Wochende nicht auf so einer Diskussion verschwenden.

**Comment by PWehr599** [comment]
Ausserdem: Lese meine Nachrichten **nochmal** genau durch. Es steht nix da von "mach ich nicht" oder ähnlichen Aussagen .Ich wollte euch nur mal um eure Meinung fragen , da ich mir mit dem SHM gerade schwer tue, d.h. ich komme nicht richtig voran an der Front. Es könnte ja sein , das jemand in der Gruppe noch Bescheid weiss. Ich tue mir schwer, da ich daran gearbeitet habe.  Ich werde das jetzt nicht persönlich nehmen und hoffen, dass du das nächste mal etwas nachdenkst bevor du solche Nachrichten schreibst. Bis Montag !

**Comment by amp-man** [comment]
@PWehr599 auf den Branch [feature_gameFieldSHM](https://github.com/amp-man/reversi/tree/feature_gameFieldSHM) habe ich dir gerade meinen fix für das GameField Shared Memory hoch geladen.

Das heißt du kannst jetzt im Thinker mit dem GameField arbeiten. Siehe dir am besten alle Kommentare in thinker.c an bei denen ich "Für Philippe" hinzu geschrieben habe. Damit solltest du den Thinker implementieren können.

Du kannst das Programm mit ./start_game auf der Kommandozeile starten.
Die GameID sollte dir auf einem Mac oder Linux computer automatisch in die Zwischenablage eingefügt werden, sodass du das Spiel im Browser öffnen kannst.

Falls du noch Fragen hast, zögere nicht dich zu melden. Wir wollen ja schließlich alle unseren Teil für das Gelingen des Syspraks beitragen ;)

**Comment by PWehr599** [comment]
Ja ich hab  am SHM echt viel Zeit verloren. Das fällt mir wirklich schwer. Ich werd mir das gleich anschauen. Vielen Dank für die Hilfe !!

**Comment by XPloadED** [comment]
> Ausserdem: Lese meine Nachrichten **nochmal** genau durch. Es steht nix da von "mach ich nicht" oder ähnlichen Aussagen .Ich wollte euch nur mal um eure Meinung fragen , da ich mir mit dem SHM gerade schwer tue, d.h. ich komme nicht richtig voran an der Front. Es könnte ja sein , das jemand in der Gruppe noch Bescheid weiss. Ich tue mir schwer, da ich daran gearbeitet habe. Ich werde das jetzt nicht persönlich nehmen und hoffen, dass du das nächste mal etwas nachdenkst bevor du solche Nachrichten schreibst. Bis Montag !

Gut, dann tuts mir leid dann hab ich das wohl misinterpretiert. Würde dann helfen wenn du konkreter schreiben würdest was du versucht hast (oder nen branch geben auf dem du probiert hast es zu lösen). Weil so kam das bei mir rüber als ~~ _ich brauch das gamefield im shared memory und solange kann ich ja die Spielzug methode nicht machen die seit knapp 2 wochen aufm Plan steht und ach ja das shm im connector ist ja "euer ding" also macht mal_. Dass du selber auch am shm was machst hast du ja nie erwähnt. Bezieht sich im prinzip alles auf den ersten satz deiner Antwort(und das timing der Anfrage), der mich zugegebn etwas getriggert hat.
 Wobei ich dann das Problem nicht versteh weshalb du überhaupt am shm sitzt wenn du da nicht weiter kommst und doch eh die think methode machen wolltest. Aber schon gut ich merk schon, communication is hard on github und ist ja jetzt auch egal. Kein stress wir haben ja noch ein paar wochen. Skype ist übrigens immer ne option, dann passieren so misverständnisse nicht so leicht + kein langes getippe. Viel erfolg noch beim thinker, wenn was ist meld dich halt nochmal.

Den fix fürs shm muss ich mir aber auch echt noch anschauen. Ich saß da heute stunden lang dran. Shared memory selber war, dachte ich mitlerweile, nie das problem (bei mir). Ich wär da jetzt nach ewigkeiten zu dem schluss gekommen dass es am malloc im parseGameField liegen muss ,welches eben einen pointer auf einen für den Prozess privaten speicherbereich im connector in das struct setzt, welches dann ins shared memory geschrieben wird (auf welchen der thinker prozess logischerweise nicht zugreifen darf da malloc kein shm erzeugt) ... wodurch im connector gameFieldToString über die data einträge laufen kann weil es dort darauf zugreigen darf, im thinker prozess an dem pointer jedoch stecken bleibt weil der scope fehlt(hätte perfekt erklärt warum die dimensionen und das gerüst beim ausgabestring passen, aber die Spielfeldeinträge dazwischen fehlen). Belastend dass das scheinbar nicht der grund war. Ein Tag für nichts gewasted ':D

**Comment by PWehr599** [comment]
Ach mach dir keinen Kopf. Das SHM hab ich halt versucht zu verändern aber da kam leider immer nur Schmarn raus man kennts ja. Ich hab da auch zahllose Stunden daran verschwendet. Danach ist man auch immer ein bisschen angepisst (ich jedenfalls).
War jetzt auch nicht schlimm, is halt n blödes Missverständnis ich drück mich das nächste mal besser aus:)

**Comment by PWehr599** [comment]
Jetzt nerv ich mal wieder;). Ich kann im thinker irgendwie nur ein leeres Spielfeld auslesen und nur mit einem leeren arbeiten. Ich hab schon probiert das gamefield im fork zu attachen an anderen Stellen im connector und in der main . Auch wenn ich eine Struct von gamefield in das SHMentry struct hinzufüge kann ich es nicht auslesen/drauf zugreifen. Es bleibt aus irgendeinem Grund leer. 
Ich werde dann den Robin am Montag fragen, ich weiss da grad echt nicht weiter

**Comment by PWehr599** [comment]
Aber die Logik für das ausrechnen der Spilezüge hab ich wenigstens fertig
